# Generated by Django 5.0 on 2026-09-01 12:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_taxi', '0032_vehiculo_estado_verificacion_vehiculo_motivo_rechazo_and_more'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoConductorTiempoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_linea', models.BooleanField(db_index=True, default=False)),
                ('disponible', models.BooleanField(db_index=True, default=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('precision_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('velocidad_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rumbo_grados', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('360'))])),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('ultima_ubicacion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_tiempo_real', to='App_taxi.conductor')),
                ('viaje_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_conductores', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Estado en tiempo real del conductor',
                'verbose_name_plural': 'Estados en tiempo real de conductores',
                'ordering': ['-ultima_ubicacion'],
                'indexes': [models.Index(fields=['disponible', 'ultima_ubicacion'], name='conductor_disponible_idx')],
            },
        ),
    ]
