# Generated by Django 5.0 on 2026-09-01 03:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_taxi', '0032_vehiculo_estado_verificacion_vehiculo_motivo_rechazo_and_more'),
        ('flota', '0002_cargar_tipos_vehiculo_iniciales'),
        ('pasajeros', '0002_crear_rol_pasajero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('buscando_conductor', 'Buscando conductor'), ('aceptado', 'Aceptado'), ('conductor_en_camino', 'Conductor en camino'), ('conductor_llego', 'Conductor llegó'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_encontrado', 'Conductor no encontrado')], db_index=True, default='buscando_conductor', max_length=30)),
                ('origen_direccion', models.CharField(max_length=255)),
                ('origen_latitud', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('origen_longitud', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('destino_direccion', models.CharField(max_length=255)),
                ('destino_latitud', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('destino_longitud', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('distancia_estimada_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duracion_estimada_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('tarifa_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tarifa_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('billetera', 'Billetera')], default='efectivo', max_length=20)),
                ('notas_pasajero', models.TextField(blank=True, default='')),
                ('motivo_cancelacion', models.TextField(blank=True, default='')),
                ('cancelado_por', models.CharField(blank=True, choices=[('pasajero', 'Pasajero'), ('conductor', 'Conductor'), ('administrador', 'Administrador'), ('sistema', 'Sistema')], default='', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada_conductor', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_topo', to='App_taxi.conductor')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='pasajeros.pasajero')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_topo', to='App_taxi.sucursal')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='flota.tipovehiculo')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_topo', to='App_taxi.vehiculo')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('buscando_conductor', 'Buscando conductor'), ('aceptado', 'Aceptado'), ('conductor_en_camino', 'Conductor en camino'), ('conductor_llego', 'Conductor llegó'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_encontrado', 'Conductor no encontrado')], default='', max_length=30)),
                ('estado_nuevo', models.CharField(choices=[('buscando_conductor', 'Buscando conductor'), ('aceptado', 'Aceptado'), ('conductor_en_camino', 'Conductor en camino'), ('conductor_llego', 'Conductor llegó'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_encontrado', 'Conductor no encontrado')], max_length=30)),
                ('observacion', models.TextField(blank=True, default='')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_viajes', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Historial de estado del viaje',
                'verbose_name_plural': 'Historiales de estados de viajes',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['estado', 'tipo_vehiculo', 'fecha_solicitud'], name='viaje_busqueda_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['pasajero', 'estado'], name='viaje_pasajero_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['conductor', 'estado'], name='viaje_conductor_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestadoviaje',
            index=models.Index(fields=['viaje', 'fecha'], name='historial_viaje_idx'),
        ),
    ]
