# Generated by Django 5.0 on 2026-09-01 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0032_vehiculo_estado_verificacion_vehiculo_motivo_rechazo_and_more'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='tarifa_acordada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio aceptado por el pasajero. Puede ser la tarifa estimada o una contraoferta.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='OfertaViaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tarifa_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_propuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mensaje', models.CharField(blank=True, default='', max_length=250)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(db_index=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_viajes', to='App_taxi.conductor')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Oferta de viaje',
                'verbose_name_plural': 'Ofertas de viajes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['viaje', 'estado'], name='oferta_viaje_estado_idx'), models.Index(fields=['conductor', 'estado'], name='oferta_conductor_est_idx')],
            },
        ),
    ]
