# Generated by Django 5.0 on 2026-09-01 18:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_viaje_tarifa_acordada_ofertaviaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pasajero_a_conductor', 'Pasajero califica al conductor'), ('conductor_a_pasajero', 'Conductor califica al pasajero')], max_length=30)),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.CharField(blank=True, default='', max_length=500)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Calificación de viaje',
                'verbose_name_plural': 'Calificaciones de viajes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['usuario_evaluado', 'tipo'], name='calificacion_evaluado_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='calificacionviaje',
            constraint=models.UniqueConstraint(fields=('viaje', 'tipo'), name='calificacion_unica_por_viaje_tipo'),
        ),
    ]
