# Generated by Django 5.0 on 2026-09-01 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_calificacionviaje_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], db_index=True, default='pendiente', max_length=20)),
                ('moneda', models.CharField(default='NIO', max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia_externa', models.CharField(blank=True, db_index=True, default='', help_text='Referencia futura de la pasarela de tarjetas.', max_length=150)),
                ('proveedor', models.CharField(blank=True, default='', help_text='Proveedor futuro del pago con tarjeta.', max_length=50)),
                ('datos_proveedor', models.JSONField(blank=True, default=dict)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_viajes_confirmados', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Pago de viaje',
                'verbose_name_plural': 'Pagos de viajes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['metodo', 'estado'], name='pago_metodo_estado_idx')],
            },
        ),
    ]
