# Generated by Django 5.0 on 2026-09-08 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_alter_viaje_destino_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='cantidad_pasajeros',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
