# Generated by Django 5.0 on 2026-09-01 02:28

import apps.cuentas.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_taxi', '0030_vehiculo_tipo_vehiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(default=apps.cuentas.models.calcular_vencimiento_invitacion)),
                ('fecha_utilizacion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_app', to='App_taxi.conductor')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_conductor_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación de conductor',
                'verbose_name_plural': 'Invitaciones de conductores',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['token', 'activa'], name='cuentas_inv_token_activo')],
            },
        ),
    ]
