# Generated by Django 5.0 on 2026-09-01 03:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0031_conductor_estado_verificacion'),
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculacionConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vinculacion', models.CharField(choices=[('empleado', 'Empleado'), ('afiliado', 'Afiliado')], default='empleado', max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada')], db_index=True, default='activa', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo_fin', models.TextField(blank=True, default='')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculaciones', to='App_taxi.conductor')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculaciones_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculaciones_conductores', to='App_taxi.sucursal')),
            ],
            options={
                'verbose_name': 'Vinculación de conductor',
                'verbose_name_plural': 'Vinculaciones de conductores',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
    ]
