# Generated by Django 5.0 on 2026-09-04 22:46

import apps.cuentas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_vinculacionconductor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacionPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(max_length=128)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(default=apps.cuentas.models.calcular_vencimiento_codigo)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('utilizado', models.BooleanField(db_index=True, default=False)),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacion_password', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de recuperación de contraseña',
                'verbose_name_plural': 'Códigos de recuperación de contraseña',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'utilizado', 'fecha_vencimiento'], name='cuentas_recuperacion_idx')],
            },
        ),
    ]
