# Generated by Django 5.0 on 2026-09-01 04:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_taxi', '0032_vehiculo_estado_verificacion_vehiculo_motivo_rechazo_and_more'),
        ('flota', '0002_cargar_tipos_vehiculo_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('moneda', models.CharField(default='NIO', max_length=10)),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_por_km', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tarifa_minima', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('factor_distancia_ruta', models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Corrige la distancia en línea recta para aproximar la ruta real.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('3.00'))])),
                ('porcentaje_comision_plataforma', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('vigencia_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('vigencia_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(blank=True, help_text='Vacío significa que la tarifa es global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_topo', to='App_taxi.sucursal')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='flota.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Tarifa de vehículo',
                'verbose_name_plural': 'Tarifas de vehículos',
                'ordering': ['tipo_vehiculo__orden', 'sucursal_id', '-vigencia_desde'],
                'indexes': [models.Index(fields=['tipo_vehiculo', 'sucursal', 'activo'], name='tarifa_tipo_sucursal_idx')],
            },
        ),
    ]
