# Generated by Django 5.0 on 2026-06-07 23:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula', models.CharField(max_length=30)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('licencia', models.CharField(max_length=50)),
                ('vencimiento_licencia', models.DateField(blank=True, null=True)),
                ('porcentaje_pago', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoAdelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de adelanto',
                'verbose_name_plural': 'Estados de adelantos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de gasto',
                'verbose_name_plural': 'Estados de gastos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de jornada',
                'verbose_name_plural': 'Estados de jornadas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de mantenimiento',
                'verbose_name_plural': 'Estados de mantenimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de vehículo',
                'verbose_name_plural': 'Estados de vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('propietario', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de gasto',
                'verbose_name_plural': 'Tipos de gastos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de mantenimiento',
                'verbose_name_plural': 'Tipos de mantenimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='JornadaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('kilometraje_inicial', models.PositiveIntegerField()),
                ('kilometraje_final', models.PositiveIntegerField()),
                ('kilometros_recorridos', models.PositiveIntegerField(default=0)),
                ('ingreso_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('porcentaje_pago_conductor', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('pago_conductor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_adelantos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pago_pendiente_conductor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_adelanto_excedente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ganancia_dueno', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='App_taxi.conductor')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas', to='App_taxi.estadojornada')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='App_taxi.sucursal')),
            ],
            options={
                'verbose_name': 'Jornada diaria',
                'verbose_name_plural': 'Jornadas diarias',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_pago_conductor', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('intervalo_cambio_aceite_km', models.PositiveIntegerField(default=5000)),
                ('intervalo_mantenimiento_km', models.PositiveIntegerField(default=10000)),
                ('alerta_previa_km', models.PositiveIntegerField(default=300)),
                ('moneda', models.CharField(default='C$', max_length=10)),
                ('sucursal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='App_taxi.sucursal')),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuraciones del sistema',
            },
        ),
        migrations.AddField(
            model_name='conductor',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='App_taxi.sucursal'),
        ),
        migrations.CreateModel(
            name='Adelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='App_taxi.conductor')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos', to='App_taxi.estadoadelanto')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='App_taxi.jornadadiaria')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='App_taxi.sucursal')),
            ],
            options={
                'verbose_name': 'Adelanto',
                'verbose_name_plural': 'Adelantos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_motor', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_combustible', models.CharField(blank=True, max_length=30, null=True)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('km_ultimo_cambio_aceite', models.PositiveIntegerField(default=0)),
                ('km_intervalo_cambio_aceite', models.PositiveIntegerField(default=5000)),
                ('km_ultimo_mantenimiento', models.PositiveIntegerField(default=0)),
                ('km_intervalo_mantenimiento', models.PositiveIntegerField(default=10000)),
                ('alerta_previa_km', models.PositiveIntegerField(default=300)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='App_taxi.estadovehiculo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='App_taxi.sucursal')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('kilometraje', models.PositiveIntegerField()),
                ('proximo_km_sugerido', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='App_taxi.estadomantenimiento')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='App_taxi.sucursal')),
                ('tipo_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='App_taxi.tipomantenimiento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='App_taxi.vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='App_taxi.vehiculo'),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='App_taxi.conductor')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='App_taxi.estadogasto')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='App_taxi.jornadadiaria')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='App_taxi.sucursal')),
                ('tipo_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='App_taxi.tipogasto')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='App_taxi.vehiculo')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='App_taxi.conductor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='App_taxi.sucursal')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='App_taxi.vehiculo')),
            ],
            options={
                'verbose_name': 'Asignación de vehículo',
                'verbose_name_plural': 'Asignaciones de vehículos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='App_taxi.rol')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='App_taxi.sucursal')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_conductor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('sucursal', 'numero'), name='unique_numero_vehiculo_por_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='jornadadiaria',
            constraint=models.UniqueConstraint(fields=('fecha', 'conductor', 'vehiculo'), name='unique_jornada_por_fecha_conductor_vehiculo'),
        ),
        migrations.AddConstraint(
            model_name='asignacionvehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('vehiculo',), name='unique_vehiculo_activo'),
        ),
        migrations.AddConstraint(
            model_name='asignacionvehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('conductor',), name='unique_conductor_activo'),
        ),
        migrations.AddConstraint(
            model_name='conductor',
            constraint=models.UniqueConstraint(fields=('sucursal', 'cedula'), name='unique_cedula_conductor_por_sucursal'),
        ),
    ]
