# Generated by Django 5.0 on 2026-06-09 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='App_taxi.sucursal'),
        ),
    ]
