# Generated by Django 5.0 on 2026-06-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0002_alter_conductor_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='App_taxi.sucursal'),
        ),
    ]
