# Generated by Django 5.0 on 2026-06-09 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0003_alter_vehiculo_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionvehiculo',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='App_taxi.sucursal'),
        ),
    ]
