# Generated by Django 5.0 on 2026-06-10 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0005_alter_jornadadiaria_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='App_taxi.sucursal'),
        ),
    ]
