# Generated by Django 5.0 on 2026-06-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0005_alter_jornadadiaria_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='fecha_inicio_licencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='numero_licencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
