# Generated by Django 5.0 on 2026-06-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0006_alter_gasto_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadadiaria',
            name='kilometraje_final',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
