# Generated by Django 5.0 on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0006_conductor_fecha_inicio_licencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adelanto',
            name='jornada',
        ),
        migrations.AddField(
            model_name='adelanto',
            name='tipo',
            field=models.CharField(choices=[('ADELANTO', 'Adelanto'), ('ABONO', 'Abono')], default='ADELANTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='adelanto',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
