# Generated by Django 5.0 on 2026-06-17 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0007_remove_adelanto_jornada_adelanto_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_jornadas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_adelantos_pendientes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ajuste_manual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='App_taxi.conductor')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_taxi.sucursal')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas', to='App_taxi.liquidacionconductor'),
        ),
    ]
