# Generated by Django 5.0 on 2026-06-13 01:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0007_alter_jornadadiaria_kilometraje_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadadiaria',
            name='monto_alquiler',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='tipo_cobro',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('alquiler', 'Alquiler')], default='porcentaje', max_length=20),
        ),
    ]
