# Generated by Django 5.0 on 2026-06-18 04:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0008_liquidacionconductor_jornadadiaria_liquidacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidacionconductor',
            options={'ordering': ['-fecha_creacion', '-id'], 'verbose_name': 'Liquidación de conductor', 'verbose_name_plural': 'Liquidaciones de conductores'},
        ),
        migrations.RemoveField(
            model_name='adelanto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='liquidacionconductor',
            name='abono_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacionconductor',
            name='ajuste_manual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacionconductor',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='App_taxi.conductor'),
        ),
        migrations.AlterField(
            model_name='liquidacionconductor',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='App_taxi.sucursal'),
        ),
        migrations.AlterField(
            model_name='liquidacionconductor',
            name='total_adelantos_pendientes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacionconductor',
            name='total_jornadas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacionconductor',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
