# Generated by Django 5.0 on 2026-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0008_jornadadiaria_monto_alquiler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='alerta_previa_km',
            field=models.PositiveIntegerField(default='300'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='intervalo_cambio_aceite_km',
            field=models.PositiveIntegerField(default='5000'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='intervalo_mantenimiento_km',
            field=models.PositiveIntegerField(default='10000'),
        ),
    ]
