# Generated by Django 5.0 on 2026-06-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0009_alter_configuracionsistema_alerta_previa_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoadelanto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadogasto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadojornada',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadomantenimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadovehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipogasto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipomantenimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='alerta_previa_km',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='intervalo_cambio_aceite_km',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='intervalo_mantenimiento_km',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
