# Generated by Django 5.0 on 2026-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0009_alter_liquidacionconductor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadadiaria',
            name='kilometraje_final',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
