# Generated by Django 5.0 on 2026-06-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0010_alter_jornadadiaria_kilometraje_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adelanto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='App_taxi.sucursal'),
        ),
    ]
