# Generated by Django 5.0 on 2026-06-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0010_estadoadelanto_activo_estadogasto_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adelanto',
            name='jornada',
        ),
    ]
