# Generated by Django 5.0 on 2026-06-18 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0011_remove_adelanto_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='adelanto',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos', to='App_taxi.jornadadiaria'),
        ),
    ]
