# Generated by Django 5.0 on 2026-06-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0011_alter_adelanto_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='licencia',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='vencimiento_licencia',
        ),
    ]
