# Generated by Django 5.0 on 2026-06-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0012_remove_conductor_licencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='porcentaje_pago',
        ),
    ]
