# Generated by Django 5.0 on 2026-07-04 17:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0013_remove_conductor_porcentaje_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadadiaria',
            name='monto_alquiler',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='tipo_cobro',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('alquiler', 'Alquiler')], default='porcentaje', max_length=20),
        ),
    ]
