# Generated by Django 5.0 on 2026-07-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0013_conductor_campos_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='km_aviso_mantenimiento',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tipomantenimiento',
            name='intervalo_km',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
