# Generated by Django 5.0 on 2026-07-07 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0014_configuracionsistema_km_aviso_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adelanto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='App_taxi.sucursal'),
        ),
    ]
