# Generated by Django 5.0 on 2026-07-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0014_configuracionsistema_km_aviso_mantenimiento_and_more'),
    ]

    operations = [
    ]
