# Generated by Django 5.0 on 2026-07-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0016_reparar_columnas_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='licencia',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='vencimiento_licencia',
        ),
    ]
