# Generated by Django 5.0 on 2026-07-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0015_alter_adelanto_sucursal'),
        ('App_taxi', '0017_remove_conductor_licencia_and_more'),
    ]

    operations = [
    ]
