# Generated by Django 5.0 on 2026-07-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_taxi", "0015_alter_adelanto_sucursal"),
    ]

    operations = [
        migrations.AlterField(
            model_name='adelanto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos', to='App_taxi.sucursal'),
        ),
    ]
