# Generated by Django 5.0 on 2026-07-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0019_sincronizar_adelanto_sucursal'),
    ]

    operations = [
    ]
