# Generated by Django 5.0 on 2026-07-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_taxi", "0020_reparar_columna_jornada_adelanto"),
    ]

    operations = []