# Generated by Django 5.0 on 2026-07-08 03:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0022_reparar_jornada_id_adelanto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('jornadas_count', models.PositiveIntegerField(default=0)),
                ('total_jornadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_adelantos_pendientes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('abono_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ajuste_manual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='App_taxi.conductor')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones', to='App_taxi.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-fecha_registro', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vehiculo', models.CharField(blank=True, max_length=150, null=True)),
                ('kilometros_recorridos', models.PositiveIntegerField(default=0)),
                ('ingreso_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pago_conductor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_liquidacion', to='App_taxi.jornadadiaria')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='App_taxi.liquidacion')),
            ],
            options={
                'verbose_name': 'Detalle de liquidación',
                'verbose_name_plural': 'Detalles de liquidación',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
