# Generated by Django 5.0 on 2026-07-13 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0023_liquidacion_detalleliquidacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('JORNADA_NO_INICIADA', 'Jornada no iniciada'), ('JORNADA_NO_CERRADA', 'Jornada no cerrada')], max_length=40)),
                ('fecha_jornada', models.DateField()),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='registronotificacion',
            constraint=models.UniqueConstraint(fields=('usuario', 'tipo', 'fecha_jornada'), name='notificacion_jornada_unica_por_usuario'),
        ),
    ]
