# Generated by Django 5.0 on 2026-07-14 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0024_dispositivonotificacion_registronotificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='App_taxi.sucursal'),
        ),
    ]
