# Generated by Django 5.0 on 2026-07-15 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0025_alter_mantenimiento_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroNotificacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAMBIO_ACEITE_PROXIMO', 'Cambio de aceite próximo'), ('CAMBIO_ACEITE_VENCIDO', 'Cambio de aceite vencido')], max_length=40)),
                ('kilometraje_objetivo', models.PositiveIntegerField()),
                ('kilometraje_detectado', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_notificacion_mantenimiento', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_notificacion_mantenimiento', to='App_taxi.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de notificación de mantenimiento',
                'verbose_name_plural': 'Registros de notificaciones de mantenimiento',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='registronotificacionmantenimiento',
            constraint=models.UniqueConstraint(fields=('usuario', 'vehiculo', 'tipo', 'kilometraje_objetivo'), name='notif_mant_unica_usuario_vehiculo_tipo_km'),
        ),
    ]
