# Generated by Django 5.0 on 2026-07-22 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0026_registronotificacionmantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('inspeccion_mecanica', 'Inspección mecánica'), ('emision_gases', 'Emisión de gases'), ('seguro_vehicular', 'Seguro vehicular'), ('seguro_pasajero', 'Seguro de pasajero')], max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='App_taxi.vehiculo')),
            ],
            options={
                'verbose_name': 'Documento de vehículo',
                'verbose_name_plural': 'Documentos de vehículos',
                'ordering': ['-fecha_vencimiento', '-id'],
                'indexes': [models.Index(fields=['vehiculo', 'tipo_documento'], name='doc_veh_tipo_idx'), models.Index(fields=['fecha_vencimiento'], name='doc_fecha_venc_idx')],
            },
        ),
    ]
