# Generated by Django 5.0 on 2026-08-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0027_documentovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='tipo_cobro',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('alquiler', 'Alquiler')], default='porcentaje', max_length=20),
        ),
    ]
