# Generated by Django 5.0 on 2026-08-23 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0028_conductor_tipo_cobro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Creación'), ('editar', 'Edición'), ('eliminar', 'Eliminación'), ('acceso', 'Inicio de sesión'), ('cierre_sesion', 'Cierre de sesión')], max_length=20)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_auditoria', to='App_taxi.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de auditoría',
                'verbose_name_plural': 'Movimientos de auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='App_taxi_mo_fecha_632e5f_idx'), models.Index(fields=['usuario', '-fecha'], name='App_taxi_mo_usuario_8a8218_idx'), models.Index(fields=['sucursal', '-fecha'], name='App_taxi_mo_sucursa_f3751b_idx'), models.Index(fields=['modulo', '-fecha'], name='App_taxi_mo_modulo_7b078a_idx')],
            },
        ),
    ]
