# Generated by Django 5.0 on 2026-09-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0029_movimientoauditoria'),
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='flota.tipovehiculo'),
        ),
    ]
