# Generated by Django 5.0 on 2026-09-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0030_vehiculo_tipo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='estado_verificacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], db_index=True, default='aprobado', max_length=20),
        ),
    ]
