# Generated by Django 5.0 on 2026-09-01 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0031_conductor_estado_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado_verificacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], db_index=True, default='aprobado', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='propietario_conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_propios', to='App_taxi.conductor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_propiedad',
            field=models.CharField(choices=[('sucursal', 'Propiedad de sucursal'), ('conductor', 'Propiedad del conductor')], db_index=True, default='sucursal', max_length=20),
        ),
    ]
