# Generated by Django 5.0 on 2026-09-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0032_vehiculo_estado_verificacion_vehiculo_motivo_rechazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='app_actualizacion_mensaje',
            field=models.CharField(default='Hay una nueva versión de Zenda disponible. Actualiza para continuar.', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='app_android_build',
            field=models.PositiveIntegerField(default=1, help_text='Build más reciente publicado en Play Store.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='app_android_build_minimo',
            field=models.PositiveIntegerField(default=1, help_text='Build mínimo permitido. Los builds inferiores deberán actualizar.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='app_android_version',
            field=models.CharField(default='1.0.0', help_text='Versión visible publicada en Play Store.', max_length=30),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='app_play_store_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
