# Generated by Django 5.0 on 2026-09-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0033_configuracionsistema_app_actualizacion_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='habilitado_zenda',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si este conductor puede utilizar la aplicación móvil Zenda.'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='origen_registro',
            field=models.CharField(choices=[('admin', 'Sistema administrativo'), ('zenda_mobile', 'Zenda móvil')], db_index=True, default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='dispositivonotificacion',
            name='origen',
            field=models.CharField(choices=[('zenda_mobile', 'Zenda móvil'), ('admin_web', 'Sistema administrativo'), ('legacy', 'Sin clasificar (legacy)')], db_index=True, default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='origen_registro',
            field=models.CharField(choices=[('admin', 'Sistema administrativo'), ('zenda_mobile', 'Zenda móvil')], db_index=True, default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='origen_registro',
            field=models.CharField(choices=[('admin', 'Sistema administrativo'), ('zenda_mobile', 'Zenda móvil')], db_index=True, default='admin', max_length=20),
        ),
    ]
