# Generated by Django 5.0 on 2026-09-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0034_conductor_habilitado_zenda_conductor_origen_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/%Y/%m/'),
        ),
    ]
