# Generated by Django 5.0 on 2026-09-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_taxi', '0035_vehiculo_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/%Y/%m/'),
        ),
    ]
